export const CLICK_MARKER_ACTION = "CLICK_MARKER_ACTION";
export const PUSH_MARKER_ITEM = "PUSH_MARKER_ITEM";

export const CLICK_POLYLINE_ACTION = "CLICK_POLYLINE_ACTION";
export const PUSH_POLYLINE_ITEM = "PUSH_POLYLINE_ITEM";
