export const CLICK_MARKER_ACTION = "CLICK_MARKER_ACTION";
export const PUSH_MARKER_ITEM = "PUSH_MARKER_ITEM";

export const CLICK_POLYLINE_ACTION = "CLICK_POLYLINE_ACTION";
export const PUSH_POLYLINE_ITEM = "PUSH_POLYLINE_ITEM";

export const CLICK_POLYGON_ACTION = "CLICK_POLYGON_ACTION";
export const PUSH_POLYGON_ITEM = "PUSH_POLYGON_ITEM";

export const CLICK_SQUARE_ACTION = "CLICK_SQUARE_ACTION";
export const PUSH_SQUARE_ITEM = "PUSH_SQUARE_ITEM";
